name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t tonymacdonald1995/magicconchshell .
    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag my-image ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}
        docker push tonymacdonald1995/magicconchshell

